+incdir+../Cores-SweRV/configs/snapshots/default
+incdir+../Cores-SweRV/design/include

//design/include/global.h
../Cores-SweRV/configs/snapshots/default/common_defines.vh
../Cores-SweRV/design/include/swerv_types.sv
//../Cores-SweRV/design/include/def.sv

../Cores-SweRV/design/swerv_wrapper.sv   
../Cores-SweRV/design/mem.sv                      
../Cores-SweRV/design/pic_ctrl.sv                      
../Cores-SweRV/design/swerv.sv   
../Cores-SweRV/design/dma_ctrl.sv                      
../Cores-SweRV/design/ifu/ifu_aln_ctl.sv            
../Cores-SweRV/design/ifu/ifu_compress_ctl.sv       
../Cores-SweRV/design/ifu/ifu_ifc_ctl.sv            
../Cores-SweRV/design/ifu/ifu_bp_ctl.sv            
../Cores-SweRV/design/ifu/ifu_ic_mem.sv            
../Cores-SweRV/design/ifu/ifu_mem_ctl.sv            
../Cores-SweRV/design/ifu/ifu_iccm_mem.sv            
../Cores-SweRV/design/ifu/ifu.sv                    
../Cores-SweRV/design/dec/dec_decode_ctl.sv         
../Cores-SweRV/design/dec/dec_gpr_ctl.sv            
../Cores-SweRV/design/dec/dec_ib_ctl.sv             
../Cores-SweRV/design/dec/dec_tlu_ctl.sv
../Cores-SweRV/design/dec/dec_trigger.sv                
../Cores-SweRV/design/dec/dec.sv   
../Cores-SweRV/design/exu/exu_alu_ctl.sv            
../Cores-SweRV/design/exu/exu_mul_ctl.sv            
../Cores-SweRV/design/exu/exu_div_ctl.sv    
../Cores-SweRV/design/exu/exu.sv                    
../Cores-SweRV/design/lsu/lsu.sv                    
../Cores-SweRV/design/lsu/lsu_clkdomain.sv                    
../Cores-SweRV/design/lsu/lsu_addrcheck.sv                    
../Cores-SweRV/design/lsu/lsu_lsc_ctl.sv                    
../Cores-SweRV/design/lsu/lsu_stbuf.sv
../Cores-SweRV/design/lsu/lsu_bus_buffer.sv
../Cores-SweRV/design/lsu/lsu_bus_intf.sv
../Cores-SweRV/design/lsu/lsu_ecc.sv
../Cores-SweRV/design/lsu/lsu_dccm_mem.sv
../Cores-SweRV/design/lsu/lsu_dccm_ctl.sv        
../Cores-SweRV/design/lsu/lsu_trigger.sv        
../Cores-SweRV/design/dbg/dbg.sv        
../Cores-SweRV/design/dmi/dmi_wrapper.v 
../Cores-SweRV/design/dmi/dmi_jtag_to_core_sync.v
../Cores-SweRV/design/dmi/rvjtag_tap.sv
../Cores-SweRV/design/lib/beh_lib.sv 
../Cores-SweRV/design/lib/mem_lib.sv 
../Cores-SweRV/design/lib/ahb_to_axi4.sv 
../Cores-SweRV/design/lib/axi4_to_ahb.sv 
